name: Create Unity Package on release tag

on: 
  [push, pull_request]

jobs:
  echo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    
    - run: |
        echo "Assets/PlayroomKit.meta" > metaList
        echo "Assets/Plugins/Playroom.meta" >> metaList
        echo "Assets/WebGLTemplates.meta" >> metaList
        find Assets/PlayroomKit/ -name \*.meta >> metaList
        find Assets/WebGLTemplates/ -name \*.meta >> metaList
        find Assets/Plugins/Playroom -name \*.meta >> metaList
        echo metaList

    - run: mkdir output

    - name: Set release version ENV
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - uses: pCYSl5EDgo/create-unitypackage@master
      with:
        package-path: 'output/playroomkit.unitypackage'
        include-files: metaList

    - uses: actions/upload-artifact@v4
      with:
        name: playroomkit.unitypackage
        path: output/playroomkit.unitypackage
